### ISSUE TITLE
Itch.io pre-launch checklist

### ISSUE THREAD

**Issue by saricden** [saricden/farzone#3]
These are the things I would like to accomplish before posting the game on Itch:

- [ ] Soo... P2P mutliplayer..? :shipit: :shipit: :shipit: 
  - [x] Abstract / optimize netcode until reasonably playable (thanks FetchBot!)
  - [ ] Implement peer movement interpolation (or maybe extrapolation? (See supertorpe's implementation in #phaser-3 channel - https://github.com/supertorpe/netcode-workbench/blob/33db48359374a162d5b8f123211065082da5e0e9/src/systems/renderers/simple-renderer.ts#L108))
  - [x] Sync map damage
  - [x] Implement `ArialPeer` and `OswaldPeer` classes
  - [x] Sync shooting GFX
  - [x] Sync `OswaldGrenade`s and `RobotoShell`s (position and "state")
  - [ ] Sync peer damage
  - [ ] Game over event
  - [ ] Invalid / failed connection handling
  - [ ] Disconnect handling
- [ ] 5 playable characters, with 5 corresponding enemy logic sets
  - [x] Roboto (player)
  - [x] Roboto (NPC)
  - [x] Arial (player)
  - [ ] Arial (NPC)
  - [x] Oswald (player)
  - [ ] Oswald (NPC)
  - [ ] Montserrat (player)
  - [ ] Montserrat (NPC)
  - [ ] Fira (player)
  - [ ] Fira (NPC)
- [x] Utilize `Light2D` and normal maps for shading / lighting effects
- [ ] Create normal maps / flipped normals for all characters
- [ ] Optimize atlas loading to save on memory overhead (clear spritesheets from cache per game)
- [ ] CPU difficulty settings (easy, medium, hard, extreme?)
- [ ] 10 maps
- [ ] 5 achievements
- [ ] At least one thing in settings (or remove settings from title screen)
- [ ] Automagically pull in contributor and sponsor GitHub names in credits
- [x] Fine tune the camera controls (don't zoom out so far)
- [x] Add responsive resizing functions (to allow for F11-fullscreen, etc.)
- [x] Optimize particle effects a bit
- [x] Tree leaves multi-layer wind effect
- [ ] Fix raycasting bug where you can shoot through walls
- [ ] At least try to make some better OST tracks lol
